name: Build Tauri App

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: '构建类型'
        required: true
        default: 'release'
        type: choice
        options:
        - release
        - test
      target_platforms:
        description: '目标平台'
        required: true
        default: 'all'
        type: choice
        options:
        - all
        - windows
        - macos
      create_release:
        description: '创建GitHub Release'
        required: false
        default: false
        type: boolean

jobs:
  build-windows:
    runs-on: windows-latest
    timeout-minutes: 30
    if: ${{ github.event.inputs.target_platforms == 'all' || github.event.inputs.target_platforms == 'windows' }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'
    
    - name: Install Rust stable
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-pc-windows-msvc
    
    - name: Install dependencies (Ubuntu only)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
    
    - name: Install frontend dependencies
      run: npm ci
    
    - name: Build the app
      run: npm run tauri build
    
    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-bundle
        path: src-tauri/target/release/bundle/msi/*.msi
        retention-days: 30
    
    - name: Upload portable Windows artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-portable
        path: src-tauri/target/release/video-space.exe
        retention-days: 30

  build-macos:
    runs-on: macos-14  # 使用macOS 14以避免macOS 15迁移警告
    timeout-minutes: 30
    if: ${{ github.event.inputs.target_platforms == 'all' || github.event.inputs.target_platforms == 'macos' }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'
    
    - name: Install Rust stable
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-apple-darwin
    
    - name: Install frontend dependencies
      run: npm ci
    
    - name: Build the app
      run: npm run tauri build
    
    - name: Upload macOS artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-bundle
        path: src-tauri/target/release/bundle/macos/*.app
        retention-days: 30
    
    - name: Upload macOS dmg
      uses: actions/upload-artifact@v4
      with:
        name: macos-dmg
        path: src-tauri/target/release/bundle/dmg/*.dmg
        retention-days: 30

  release:
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.create_release == 'true' && (github.event.inputs.build_type == 'release') }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Download Windows artifacts
      uses: actions/download-artifact@v4
      with:
        name: windows-bundle
        path: artifacts/windows/
    
    - name: Download Windows portable artifacts
      uses: actions/download-artifact@v4
      with:
        name: windows-portable
        path: artifacts/windows-portable/
    
    - name: Download macOS artifacts
      uses: actions/download-artifact@v4
      with:
        name: macos-dmg
        path: artifacts/macos/
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/windows/*.msi
          artifacts/windows-portable/video-space.exe
          artifacts/macos/*.dmg
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check-build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'
    
    - name: Install Rust stable
      uses: dtolnay/rust-toolchain@stable
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
    
    - name: Install frontend dependencies
      run: npm ci
    
    - name: Check Tauri configuration
      run: npm run tauri info
    
    - name: Validate project structure
      run: |
        if [ ! -f "tauri.conf.json" ]; then
          echo "Error: tauri.conf.json not found"
          exit 1
        fi
        if [ ! -d "src-tauri" ]; then
          echo "Error: src-tauri directory not found"
          exit 1
        fi
        if [ ! -f "src-tauri/Cargo.toml" ]; then
          echo "Error: Cargo.toml not found in src-tauri"
          exit 1
        fi
    
    - name: Run lint checks
      run: |
        if command -v npm audit &> /dev/null; then
          npm audit --audit-level moderate
        fi
    
    - name: Upload validation results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: validation-results
        path: |
          package-lock.json
          Cargo.lock
        retention-days: 7